_BASE_: "Base-TridentNet-Fast-C4_3branch_res3stride1_giou.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    NORM: "GN"
  BACKBONE:
    FREEZE_AT: 0
  RPN:
    BBOX_REG_LOSS_TYPE: "giou"
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "giou"