MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_trident_resnet_backbone"
  ROI_HEADS:
    NAME: "TridentRes5ROIHeads"
    NUM_CLASSES: 3
  PROPOSAL_GENERATOR:
    NAME: "TridentRPN"
  TRIDENT:
    NUM_BRANCH: 1
    BRANCH_DILATIONS: [1]
    TEST_BRANCH_IDX: -1
    TRIDENT_STAGE: "res4"
DATASETS:
#  TRAIN: ("coco_2017_train",)
#  TEST: ("coco_2017_val",)
  TRAIN: ("ued_trainval",)
  TEST: ("ued_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (40000, 55000)
  MAX_ITER: 60000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
