MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_trident_resnet_backbone"
  ROI_HEADS:
    NAME: "TridentRes5ROIHeads"
    POSITIVE_FRACTION: 0.5
    BATCH_SIZE_PER_IMAGE: 128
    PROPOSAL_APPEND_GT: False
    NUM_CLASSES: 3
  PROPOSAL_GENERATOR:
    NAME: "ATSSRPN"
  ANCHOR_GENERATOR:
    SIZES: [[8, 16, 32, 64, 128]]
    ASPECT_RATIOS: [[0.5, 0.75, 1.0, 1.5, 2.0]]
  RPN:
    POST_NMS_TOPK_TRAIN: 500
  TRIDENT:
    NUM_BRANCH: 1
    BRANCH_DILATIONS: [1]
    TEST_BRANCH_IDX: -1
    TRIDENT_STAGE: "res4"
  ATSS:
    POSITIVE_TYPE: 'ATSS'
    TOPK: 25
  #WEIGHTS: "modelzoo/R-50-GN.pkl"
DATASETS:
#  TRAIN: ("coco_2017_train",)
#  TEST: ("coco_2017_val",)
  TRAIN: ("ued_trainval",)
  TEST: ("ued_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.005
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
