MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_trident_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4"]
  FPN:
    IN_FEATURES: ["res3", "res4"]
    OUT_CHANNELS: 768
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p3", "p4"]
    PRE_NMS_TOPK_TRAIN: 6000  # Per FPN level
    PRE_NMS_TOPK_TEST: 3000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    IN_FEATURES: ["p3", "p4"]
    NUM_CLASSES: 3
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  TRIDENT:
    NUM_BRANCH: 1
    BRANCH_DILATIONS: [1]
    TEST_BRANCH_IDX: -1
    TRIDENT_STAGE: "res4"
DATASETS:
  ## TRAIN: ("coco_2017_train",)
  ## TEST: ("coco_2017_val",)
  TRAIN: ("ued_trainval",)
  TEST: ("ued_test",)
SOLVER:
  ##IMS_PER_BATCH: 16
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
